export type ErrorResponseType =
	"UNKNOWN" |
	"TIMEOUT" |

	"INVALID_REQUEST" |

	"MISSING_TOKEN" |
	"INVALID_TOKEN" |
	"TOKEN_EXPIRED" |
	"MISSING_ACCESS" |

	"WRONG_PASSWORD" |

	"SKILL_NOT_FOUND" |
	"SKILL_ALREADY_EXISTS" |
	"USER_NOT_FOUND" |
	"USER_ALREADY_EXISTS" |
	"TEAM_NOT_FOUND" |
	"TEAM_ALREADY_EXISTS" |
	"MEETING_NOT_FOUND" |
	"MEETING_ALREADY_EXISTS" |

	"FILE_NOT_FOUND" |
	"INVALID_FILE_TYPE" |

	"ALREADY_PARTICIPATING" |
	"PARTICIPANT_NOT_FOUND"

export interface ErrorResponse {
	status: number,
	type: ErrorResponseType
}